CREATE SCHEMA config;
CREATE SCHEMA registr;
CREATE SCHEMA report;
CREATE SCHEMA inform;
CREATE SCHEMA mfc;
CREATE SCHEMA econom;
CREATE SCHEMA office;
CREATE SCHEMA expert;
CREATE SCHEMA dict;

CREATE SCHEMA schet;
